#4g无线原始数据目录
wuxian_base_dir: /data/cmdi\ZJproject\ZJ_AIOPS_ch_v2\data/告警/全量告警1116-1122/无线/
#5g原始数据目录
wug_base_dir : /data/cmdi\ZJproject\ZJ_AIOPS_ch_v2\data/告警/全量告警1116-1122/5G/
#告警分类表路径
Warn_table_dir: ./config/配置文档1：隐患识别规则配置页面--告警影响权重配置.xlsx
#统计结果 目录
Alert_to_base: ./result/
#总基站数文件 路径
alert_num_path: ./config/网络信息_全省_2020-10-17.xlsx
#开始日期
start : '1116'
#结束日期
end: '1122'
#年份
year: '2020'
#中间数据根目录
orgpath: ./tmp/

#工单数据目录
wo_dir: ./data/wo/


